# Basic Plugin Info
name: EnhancedPets
version: 1.0.0
main: dev.asteriamc.enhancedpets.Enhancedpets
api-version: 1.17
authors: [AxolotlSMP]
description: Enhances pet management in Minecraft.
website: fun.axosmp.com
namespace: fun.axosmp.enhancedpets
commands:
  pets:
    description: Manage your enhanced pets via a GUI or reload config.
    usage: /<command> [reload]
    permission: enhancedpets.use
    aliases: [pet, mypets, ep]
permissions:
  enhancedpets.use:
    description: Allows using the /pets command GUI to manage owned pets.
    default: true
  enhancedpets.reload:
    description: Allows using /<command> reload to reload the plugin configuration.
    default: op
  enhancedpets.admin:
    description: Allows access to administrative features (currently includes reload).
    default: op
